server {
    listen 80;
    server_name _;

    root /var/www/html;
    index index.html index.htm;

    location / {
        root /var/www/html;
        index index.html index.htm;
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, OPTIONS";
        try_files $uri $uri/ =404;
    }

    location ~* \.(mpd|m4s|mp4)$ {
        root /var/www/html;
        add_header Access-Control-Allow-Origin *;
        add_header Content-Type application/octet-stream;
    }
}
